### ISSUE TITLE
Digital Ocean - Cannot open Editor

### ISSUE THREAD

**Issue by Mbessing** [flowforge/flowforge#2006]
### Current Behavior

I created a droplet on Digital Ocean following the guide on the Flowforge website. I bought a domain, setup the DNS wildcard entry and everything. I am now able to access flowforge on the domain with forge.domain, however when I try to open the editor, the browser gets blank and the url in the browser says: about:blank

Is this me doing something wrong?

![Skærmbillede 2023-04-14 093937](https://user-images.githubusercontent.com/85192438/231977112-a9cc58e7-9f02-4de9-8362-46502e25cc57.png)

![Skærmbillede 2023-04-14 092159](https://user-images.githubusercontent.com/85192438/231976830-d10bc87b-bc60-4d2b-a74b-dbb0504a14b4.png)

### Expected Behavior

I expected the editor to show as it normally does when I click "Open Editor" rather than a blank page.

### Steps To Reproduce

I simply followed the guide on Flowforge's website 

### Environment

- FlowForge version: v1.5.0
- Node.js version: v17.7.1
- npm version: v8.5.2
- Platform/OS: Windows 11
- Browser: Google Chrome

**Comment by hardillb** [comment]
Please try clicking on the instance name at the left hand end of the row, and then clicking on the editor link at the top of the overview page.

This should open the editor.

**Comment by hardillb** [comment]
Also I think this should have been fixed with the release of 1.6.0 yesterday. To upgrade you can do the following:

Log into the droplet with SSH or accessing the console from the DO Console then run the following commands:

- `cd /opt/flowforge`
- `docker compose -p flowforge down`
- `docker pull flowforge/forge-docker`
- `docker pull flowforge/file-server`
- `docker pull flowforge/node-red`
- `docker compose -p flowforge up -d`

The new version of the droplet will be available in the market place shortly

**Comment by Mbessing** [comment]
Thank you, I ran the suggested commands. The problem still seem to exist: 

![Skærmbillede 2023-04-15 002247](https://user-images.githubusercontent.com/85192438/232164807-6d441570-7001-4d56-915e-1bf4fa6714f8.png)
![Skærmbillede 2023-04-15 002427](https://user-images.githubusercontent.com/85192438/232164810-0b0c45dd-f243-4159-93a0-75a43f75cb4c.png)

**Comment by Mbessing** [comment]
Could this be related to the issue? 

![Skærmbillede 2023-04-15 002545](https://user-images.githubusercontent.com/85192438/232164924-5806ceaf-4b98-49cd-b40b-ec8b1dc348c0.png)

**Comment by knolleary** [comment]
Hi @Mbessing 

It looks like you have a typo in your configuration:

<img width="62" alt="image" src="https://user-images.githubusercontent.com/51083/232449669-4f7639d5-17fe-4688-953d-9053f4487005.png">

`httpss` should be `https`.

**Comment by Mbessing** [comment]
Thank you, it does not work with https either.

**Comment by ZJvandeWeg** [comment]
@Mbessing Did you restart the FlowForge instance to reload the config changes?

**Comment by joepavitt** [comment]
@Mbessing did you get anywhere with this. We're doing a sweep of older issues, and noticed this was stale. Will close as stale, but please do re-open if assistance still required
